### ISSUE TITLE
Request for joining the organisation

### ISSUE THREAD

**Issue by riturajjain2000** [jobream/Leetcode-Company-Wise-Problems#2]
Hello, my name is Rituraj. I am from India.
I would like to join this organization.
I love to contribute to open source and will love to contribute to this organization.
Please add me to your organization.

**Comment by MrSlimCoder** [comment]
@amanjainn please add them to Jobream.

**Comment by MrSlimCoder** [comment]
@riturajjain2000 Check invitation
